module.exports = {
  'SENDGRID_APIKEY': process.env.SENDGRID_APIKEY,
  'SENDGRID_FROM_EMAIL': process.env.SENDGRID_FROM_EMAIL,
  'KEYPAY_CLIENT_ID': process.env.KEYPAY_CLIENT_ID,
  'KEYPAY_REDIRECT_URL': process.env.KEYPAY_REDIRECT_URL,
  'KEYPAY_TOKEN_URL': process.env.KEYPAY_TOKEN_URL,
  'KEYPAY_CLIENT_SECRET': process.env.KEYPAY_CLIENT_SECRET,
  'KEYPAY_GRANT_TYPE': process.env.KEYPAY_GRANT_TYPE,
  'XERO_CLIENT_ID': process.env.XERO_CLIENT_ID,
  'XERO_CLIENT_SECRET': process.env.XERO_CLIENT_SECRET,
  'XERO_REDIRECT_URL': process.env.XERO_REDIRECT_URL,
  'DEPUTY_CLIENT_ID': process.env.DEPUTY_CLIENT_ID,
  'DEPUTY_REDIRECT_URL': process.env.DEPUTY_REDIRECT_URL,
  "DEPUTY_CLIENT_SECRET": process.env.DEPUTY_CLIENT_SECRET,
  "RECKON_CLIENT_ID": process.env.RECKON_CLIENT_ID,
  "RECKON_REDIRECT_URL": process.env.RECKON_REDIRECT_URL,
  "RECKON_CLIENT_SECRET": process.env.RECKON_CLIENT_SECRET,
  "HR3_API_URL": process.env.HR3_API_URL
};
